# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('path_raw', models.CharField(max_length=255)),
                ('path_scaled', models.CharField(max_length=255)),
                ('path_thumb', models.CharField(max_length=155)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
